#!/bin/sh
# remove backup files

if [ -z "$RPM_BUILD_ROOT" ]; then
    echo "No build root defined" >&2
    exit 1
fi

if [ ! -d "$RPM_BUILD_ROOT" ]; then
    echo "Invalid build root" >&2
    exit 1
fi

find "$RPM_BUILD_ROOT" \( -type f -o -type l \) \( \
	-name '#*#' -o \
	-name \*.orig -o \
	-name \*~ -o \
	-name DEADJOE -o \
	-name .cvsignore -o \
	-name \*.orig -o \
	-name \*.rej -o \
	-name \*.bak -o \
	-name \*.SUMS -o \
	-name TAGS -o \
	-name .deps -o \
	-name .P -o \
	-name core \) \
	-delete

find "$RPM_BUILD_ROOT" -type d -name CVS | xargs rm -rf
