#!/bin/sh
# convert end of line patterns from DOS to UNIX

if [ -z "$RPM_BUILD_ROOT" ]; then
    echo "No build root defined" >&2
    exit 1
fi

if [ ! -d "$RPM_BUILD_ROOT" ]; then
    echo "Invalid build root" >&2
    exit 1
fi

for f in `find "$RPM_BUILD_ROOT" -type f`; do
    if [ -n "$EXCLUDE_FROM_EOL_CONVERSION" ]; then
	basename "$f" | grep -q -P "$EXCLUDE_FROM_EOL_CONVERSION" && continue
    fi
    grep -q -Ilsr $'\r$' "$f" && sed -e 's/\r$//' -i "$f"
done

exit 0
