#!/bin/sh
# $Id$
# convert end of line patterns from DOS to UNIX

if [ -z "$RPM_BUILD_ROOT" ]; then
    echo "No build root defined" >&2
    exit 1
fi

if [ ! -d "$RPM_BUILD_ROOT" ]; then
    echo "Invalid build root" >&2
    exit 1
fi

for f in `find "$RPM_BUILD_ROOT" \( -type f -o -type l \)`; do
    grep -q -Ilsr $'\r$' "$f" && sed -e 's/\r$//' -i "$f"
done
